name: open_screen_studio
description: An opinionated screen recording and editing app for Windows built with Flutter Desktop.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  window_manager: ^0.3.7
  media_kit: ^1.1.10
  media_kit_video: ^1.2.4
  media_kit_libs_windows_video: ^1.0.9
  path: ^1.8.3
  flutter_colorpicker: ^1.0.3
  google_fonts: ^6.1.0
  path_provider: ^2.1.1
  screen_capturer: ^0.1.7
  ffi: ^2.1.0
  win32: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/cursors/
